version: "3.9"
services:
  web:
    image: aiallen/tsmc-project:rq-dashboard
    build:
      context: .
      target: web
    ports:
      - "8000:5000"
    volumes:
      - ./frontend:/tsmc-project/frontend
    environment:
      FLASK_ENV: development

  nodeserver:
    image: aiallen/tsmc-project:nodeserver
    build:
      context: .
      target: nodeserver

  crawler:
    image: aiallen/tsmc-project:crawler
    build:
      context: .
      target: crawler
    # volumes:
    #   - ./crawler:/tsmc-project/crawler

  crawler-controller:
    image: aiallen/tsmc-project:crawler-controller
    build:
      context: .
      target: crawler-controller

  worker:
    image: aiallen/tsmc-project:worker
    build:
      context: .
      target: worker
    # volumes:
    #   - ./worker:/tsmc-project/worker

  redis:
    image: "redis:alpine"
    # hostname: redis
  mongodb-server:
    image: "mongo"
    # hostname: mongodb-server
