apiVersion: v1
kind: Pod
metadata:
  name: mongodb-server
spec:
  hostNetwork: true
  containers:
  - name: mongodb-server
    image: mongo
    imagePullPolicy: IfNotPresent 
    ports:
      - containerPort: 27017