apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
spec:
  schedule: "0 0 * * 1"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: crawler
              image: aiallen/tsmc-project:crawler
              imagePullPolicy: Always
          restartPolicy: OnFailure
