apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: nodeserver-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodeserver-service
            port:
              number: 3000