apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: crawler
            image: chkao777/tsmc-project:crawler
            imagePullPolicy: Always     
          restartPolicy: OnFailure